actionbase:
  tenant: ab-local
  datastore:
    type: hbase
    configuration:
      actionbase.hbase.namespace: ab_local
      hbase.zookeeper.quorum: hbase:2181

logging:
  file:
    name: /app/logs/actionbase.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5
      total-size-cap: 50MB
  level:
    com.kakao.actionbase: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.http.server.reactive: DEBUG
    reactor.netty.http.server: DEBUG
  threshold:
    console: OFF
    file: DEBUG
